package model;
// Generated 14-Mar-2016 19:47:15 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Aeroporto generated by hbm2java
 */
@Entity
@Table(name="aeroporto"
    ,catalog="vvv"
)
public class Aeroporto  implements java.io.Serializable {


     private String identificador;
     private Cidade cidade;
     private String nome;

    public Aeroporto() {
    }

    public Aeroporto(String identificador, Cidade cidade, String nome) {
       this.identificador = identificador;
       this.cidade = cidade;
       this.nome = nome;
    }
   
     @Id 

    
    @Column(name="identificador", unique=true, nullable=false, length=3)
    public String getIdentificador() {
        return this.identificador;
    }
    
    public void setIdentificador(String identificador) {
        this.identificador = identificador;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Cidade_id", nullable=false)
    public Cidade getCidade() {
        return this.cidade;
    }
    
    public void setCidade(Cidade cidade) {
        this.cidade = cidade;
    }

    
    @Column(name="nome", nullable=false)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }




}


