package model;
// Generated 13-Mar-2016 14:26:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cidade generated by hbm2java
 */
@Entity
@Table(name="cidade"
    ,catalog="vvv"
)
public class Cidade  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private String uf;
     private String pais;
     private Set<Viagem> viagemsForCidadeDestinoId = new HashSet<Viagem>(0);
     private Set<Viagem> viagemsForCidadeOrigemId = new HashSet<Viagem>(0);
     private Set<Escala> escalasForCidadeDestinoId = new HashSet<Escala>(0);
     private Set<Escala> escalasForCidadeOrigemId = new HashSet<Escala>(0);

    public Cidade() {
    }

	
    public Cidade(String nome, String uf, String pais) {
        this.nome = nome;
        this.uf = uf;
        this.pais = pais;
    }
    public Cidade(String nome, String uf, String pais, Set<Viagem> viagemsForCidadeDestinoId, Set<Viagem> viagemsForCidadeOrigemId, Set<Escala> escalasForCidadeDestinoId, Set<Escala> escalasForCidadeOrigemId) {
       this.nome = nome;
       this.uf = uf;
       this.pais = pais;
       this.viagemsForCidadeDestinoId = viagemsForCidadeDestinoId;
       this.viagemsForCidadeOrigemId = viagemsForCidadeOrigemId;
       this.escalasForCidadeDestinoId = escalasForCidadeDestinoId;
       this.escalasForCidadeOrigemId = escalasForCidadeOrigemId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nome", nullable=false, length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="uf", nullable=false, length=3)
    public String getUf() {
        return this.uf;
    }
    
    public void setUf(String uf) {
        this.uf = uf;
    }

    
    @Column(name="pais", nullable=false, length=45)
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cidadeByCidadeDestinoId")
    public Set<Viagem> getViagemsForCidadeDestinoId() {
        return this.viagemsForCidadeDestinoId;
    }
    
    public void setViagemsForCidadeDestinoId(Set<Viagem> viagemsForCidadeDestinoId) {
        this.viagemsForCidadeDestinoId = viagemsForCidadeDestinoId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cidadeByCidadeOrigemId")
    public Set<Viagem> getViagemsForCidadeOrigemId() {
        return this.viagemsForCidadeOrigemId;
    }
    
    public void setViagemsForCidadeOrigemId(Set<Viagem> viagemsForCidadeOrigemId) {
        this.viagemsForCidadeOrigemId = viagemsForCidadeOrigemId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cidadeByCidadeDestinoId")
    public Set<Escala> getEscalasForCidadeDestinoId() {
        return this.escalasForCidadeDestinoId;
    }
    
    public void setEscalasForCidadeDestinoId(Set<Escala> escalasForCidadeDestinoId) {
        this.escalasForCidadeDestinoId = escalasForCidadeDestinoId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cidadeByCidadeOrigemId")
    public Set<Escala> getEscalasForCidadeOrigemId() {
        return this.escalasForCidadeOrigemId;
    }
    
    public void setEscalasForCidadeOrigemId(Set<Escala> escalasForCidadeOrigemId) {
        this.escalasForCidadeOrigemId = escalasForCidadeOrigemId;
    }




}


