package model;
// Generated 14-Mar-2016 19:47:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Cidade generated by hbm2java
 */
@Entity
@Table(name="cidade"
    ,catalog="vvv"
    , uniqueConstraints = @UniqueConstraint(columnNames="identificador") 
)
public class Cidade  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private String identificador;
     private String pais;
     private Set<Escala> escalasForCidadeDestinoId = new HashSet<Escala>(0);
     private Set<Aeroporto> aeroportos = new HashSet<Aeroporto>(0);
     private Set<Escala> escalasForCidadeOrigemId = new HashSet<Escala>(0);

    public Cidade() {
    }

	
    public Cidade(String nome, String identificador, String pais) {
        this.nome = nome;
        this.identificador = identificador;
        this.pais = pais;
    }
    public Cidade(String nome, String identificador, String pais, Set<Escala> escalasForCidadeDestinoId, Set<Aeroporto> aeroportos, Set<Escala> escalasForCidadeOrigemId) {
       this.nome = nome;
       this.identificador = identificador;
       this.pais = pais;
       this.escalasForCidadeDestinoId = escalasForCidadeDestinoId;
       this.aeroportos = aeroportos;
       this.escalasForCidadeOrigemId = escalasForCidadeOrigemId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nome", nullable=false)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="identificador", unique=true, nullable=false, length=3)
    public String getIdentificador() {
        return this.identificador;
    }
    
    public void setIdentificador(String identificador) {
        this.identificador = identificador;
    }

    
    @Column(name="pais", nullable=false)
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cidadeByCidadeDestinoId")
    public Set<Escala> getEscalasForCidadeDestinoId() {
        return this.escalasForCidadeDestinoId;
    }
    
    public void setEscalasForCidadeDestinoId(Set<Escala> escalasForCidadeDestinoId) {
        this.escalasForCidadeDestinoId = escalasForCidadeDestinoId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cidade")
    public Set<Aeroporto> getAeroportos() {
        return this.aeroportos;
    }
    
    public void setAeroportos(Set<Aeroporto> aeroportos) {
        this.aeroportos = aeroportos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cidadeByCidadeOrigemId")
    public Set<Escala> getEscalasForCidadeOrigemId() {
        return this.escalasForCidadeOrigemId;
    }
    
    public void setEscalasForCidadeOrigemId(Set<Escala> escalasForCidadeOrigemId) {
        this.escalasForCidadeOrigemId = escalasForCidadeOrigemId;
    }




}


