package model;
// Generated 13-Mar-2016 22:50:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="cliente"
    ,catalog="vvv"
    , uniqueConstraints = @UniqueConstraint(columnNames="cpf") 
)
public class Cliente  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private int idade;
     private String cpf;
     private String telefone;
     private String profissao;
     private Set<Reserva> reservas = new HashSet<Reserva>(0);

    public Cliente() {
    }

	
    public Cliente(String nome, int idade, String cpf, String telefone) {
        this.nome = nome;
        this.idade = idade;
        this.cpf = cpf;
        this.telefone = telefone;
    }
    public Cliente(String nome, int idade, String cpf, String telefone, String profissao, Set<Reserva> reservas) {
       this.nome = nome;
       this.idade = idade;
       this.cpf = cpf;
       this.telefone = telefone;
       this.profissao = profissao;
       this.reservas = reservas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nome", nullable=false, length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="idade", nullable=false)
    public int getIdade() {
        return this.idade;
    }
    
    public void setIdade(int idade) {
        this.idade = idade;
    }

    
    @Column(name="cpf", unique=true, nullable=false, length=11)
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    
    @Column(name="telefone", nullable=false, length=45)
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    
    @Column(name="profissao", length=45)
    public String getProfissao() {
        return this.profissao;
    }
    
    public void setProfissao(String profissao) {
        this.profissao = profissao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cliente")
    public Set<Reserva> getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set<Reserva> reservas) {
        this.reservas = reservas;
    }




}


