package model;
// Generated 14-Mar-2016 19:47:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.*;
import org.hibernate.validator.constraints.*;
import org.hibernate.validator.constraints.br.CPF;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="cliente"
    ,catalog="vvv"
    , uniqueConstraints = @UniqueConstraint(columnNames="cpf") 
)
public class Cliente  implements java.io.Serializable {


     private Integer id;
     
     @NotBlank(message = "VAZIO")
     @Size(min = 2, max = 256, message = "TAMANHO")
     private String nome;
     
     @NotBlank(message = "VAZIO")
     @CPF(message = "TAMANHO")
     private String cpf;
     
     @NotBlank(message = "VAZIO")
     @Size(min = 3, max = 32, message = "TAMANHO")
     private String telefone;
     
     @NotBlank(message = "VAZIO")
     private String profissao;
     
     @NotBlank(message = "VAZIO")
     @Size(min = 3, max = 256, message = "TAMANHO")
     private String endereco;
     
     @Min(value = 0, message = "INVALIDO")
     private int idade;
     private Set<Reserva> reservas = new HashSet<>(0);

    public Cliente() {
    }

	
    public Cliente(String nome, String cpf, String telefone, String profissao, String endereco, int idade) {
        this.nome = nome;
        this.cpf = cpf;
        this.telefone = telefone;
        this.profissao = profissao;
        this.endereco = endereco;
        this.idade = idade;
    }
    public Cliente(String nome, String cpf, String telefone, String profissao, String endereco, int idade, Set<Reserva> reservas) {
       this.nome = nome;
       this.cpf = cpf;
       this.telefone = telefone;
       this.profissao = profissao;
       this.endereco = endereco;
       this.idade = idade;
       this.reservas = reservas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nome", nullable=false)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="cpf", unique=true, nullable=false, length=11)
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    
    @Column(name="telefone", nullable=false, length=32)
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    
    @Column(name="profissao", nullable=false, length=64)
    public String getProfissao() {
        return this.profissao;
    }
    
    public void setProfissao(String profissao) {
        this.profissao = profissao;
    }

    
    @Column(name="endereco", nullable=false)
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    
    @Column(name="idade", nullable=false)
    public int getIdade() {
        return this.idade;
    }
    
    public void setIdade(int idade) {
        this.idade = idade;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cliente")
    public Set<Reserva> getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set<Reserva> reservas) {
        this.reservas = reservas;
    }




}


