package model;
// Generated Mar 2, 2016 5:55:12 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer idCliente;
     private String nome;
     private Integer idade;
     private Integer cpf;
     private String telefone;
     private String profissao;
     private Set reservas = new HashSet(0);

    public Cliente() {
    }

    public Cliente(String nome, Integer idade, Integer cpf, String telefone, String profissao, Set reservas) {
       this.nome = nome;
       this.idade = idade;
       this.cpf = cpf;
       this.telefone = telefone;
       this.profissao = profissao;
       this.reservas = reservas;
    }
   
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Integer getIdade() {
        return this.idade;
    }
    
    public void setIdade(Integer idade) {
        this.idade = idade;
    }
    public Integer getCpf() {
        return this.cpf;
    }
    
    public void setCpf(Integer cpf) {
        this.cpf = cpf;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getProfissao() {
        return this.profissao;
    }
    
    public void setProfissao(String profissao) {
        this.profissao = profissao;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }




}


