package model;
// Generated 13-Mar-2016 14:26:24 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Escala generated by hbm2java
 */
@Entity
@Table(name="escala"
    ,catalog="vvv"
)
public class Escala  implements java.io.Serializable {


     private Integer id;
     private Cidade cidadeByCidadeDestinoId;
     private Cidade cidadeByCidadeOrigemId;
     private Modal modal;
     private Viagem viagem;
     private Date saida;
     private Date chegada;

    public Escala() {
    }

    public Escala(Cidade cidadeByCidadeDestinoId, Cidade cidadeByCidadeOrigemId, Modal modal, Viagem viagem, Date saida, Date chegada) {
       this.cidadeByCidadeDestinoId = cidadeByCidadeDestinoId;
       this.cidadeByCidadeOrigemId = cidadeByCidadeOrigemId;
       this.modal = modal;
       this.viagem = viagem;
       this.saida = saida;
       this.chegada = chegada;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cidade_destino_id", nullable=false)
    public Cidade getCidadeByCidadeDestinoId() {
        return this.cidadeByCidadeDestinoId;
    }
    
    public void setCidadeByCidadeDestinoId(Cidade cidadeByCidadeDestinoId) {
        this.cidadeByCidadeDestinoId = cidadeByCidadeDestinoId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cidade_origem_id", nullable=false)
    public Cidade getCidadeByCidadeOrigemId() {
        return this.cidadeByCidadeOrigemId;
    }
    
    public void setCidadeByCidadeOrigemId(Cidade cidadeByCidadeOrigemId) {
        this.cidadeByCidadeOrigemId = cidadeByCidadeOrigemId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="modal_id", nullable=false)
    public Modal getModal() {
        return this.modal;
    }
    
    public void setModal(Modal modal) {
        this.modal = modal;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="viagem_id", nullable=false)
    public Viagem getViagem() {
        return this.viagem;
    }
    
    public void setViagem(Viagem viagem) {
        this.viagem = viagem;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="saida", nullable=false, length=19)
    public Date getSaida() {
        return this.saida;
    }
    
    public void setSaida(Date saida) {
        this.saida = saida;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="chegada", nullable=false, length=19)
    public Date getChegada() {
        return this.chegada;
    }
    
    public void setChegada(Date chegada) {
        this.chegada = chegada;
    }




}


