package model;
// Generated Mar 2, 2016 5:55:12 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Escala generated by hbm2java
 */
public class Escala  implements java.io.Serializable {


     private Integer idEscala;
     private Cidade cidadeByCidadeId1;
     private Cidade cidadeByCidadeId;
     private Modal modal;
     private Viagem viagem;
     private Date saida;
     private Date chegada;

    public Escala() {
    }

	
    public Escala(Cidade cidadeByCidadeId1, Cidade cidadeByCidadeId, Viagem viagem) {
        this.cidadeByCidadeId1 = cidadeByCidadeId1;
        this.cidadeByCidadeId = cidadeByCidadeId;
        this.viagem = viagem;
    }
    public Escala(Cidade cidadeByCidadeId1, Cidade cidadeByCidadeId, Modal modal, Viagem viagem, Date saida, Date chegada) {
       this.cidadeByCidadeId1 = cidadeByCidadeId1;
       this.cidadeByCidadeId = cidadeByCidadeId;
       this.modal = modal;
       this.viagem = viagem;
       this.saida = saida;
       this.chegada = chegada;
    }
   
    public Integer getIdEscala() {
        return this.idEscala;
    }
    
    public void setIdEscala(Integer idEscala) {
        this.idEscala = idEscala;
    }
    public Cidade getCidadeByCidadeId1() {
        return this.cidadeByCidadeId1;
    }
    
    public void setCidadeByCidadeId1(Cidade cidadeByCidadeId1) {
        this.cidadeByCidadeId1 = cidadeByCidadeId1;
    }
    public Cidade getCidadeByCidadeId() {
        return this.cidadeByCidadeId;
    }
    
    public void setCidadeByCidadeId(Cidade cidadeByCidadeId) {
        this.cidadeByCidadeId = cidadeByCidadeId;
    }
    public Modal getModal() {
        return this.modal;
    }
    
    public void setModal(Modal modal) {
        this.modal = modal;
    }
    public Viagem getViagem() {
        return this.viagem;
    }
    
    public void setViagem(Viagem viagem) {
        this.viagem = viagem;
    }
    public Date getSaida() {
        return this.saida;
    }
    
    public void setSaida(Date saida) {
        this.saida = saida;
    }
    public Date getChegada() {
        return this.chegada;
    }
    
    public void setChegada(Date chegada) {
        this.chegada = chegada;
    }




}


