package model;
// Generated 13-Mar-2016 14:26:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Funcionario generated by hbm2java
 */
@Entity
@Table(name="funcionario"
    ,catalog="vvv"
    , uniqueConstraints = {@UniqueConstraint(columnNames="cpf"), @UniqueConstraint(columnNames="userName")} 
)
public class Funcionario  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private String endereco;
     private String telefone;
     private int cargo;
     private byte[] password;
     private String userName;
     private int cpf;
     private Set<Reserva> reservas = new HashSet<Reserva>(0);
     private Set<PontodevendaFuncionario> pontodevendaFuncionarios = new HashSet<PontodevendaFuncionario>(0);
     private Set<Pontodevenda> pontodevendas = new HashSet<Pontodevenda>(0);

    public Funcionario() {
    }

	
    public Funcionario(String nome, String endereco, String telefone, int cargo, byte[] password, String userName, int cpf) {
        this.nome = nome;
        this.endereco = endereco;
        this.telefone = telefone;
        this.cargo = cargo;
        this.password = password;
        this.userName = userName;
        this.cpf = cpf;
    }
    public Funcionario(String nome, String endereco, String telefone, int cargo, byte[] password, String userName, int cpf, Set<Reserva> reservas, Set<PontodevendaFuncionario> pontodevendaFuncionarios, Set<Pontodevenda> pontodevendas) {
       this.nome = nome;
       this.endereco = endereco;
       this.telefone = telefone;
       this.cargo = cargo;
       this.password = password;
       this.userName = userName;
       this.cpf = cpf;
       this.reservas = reservas;
       this.pontodevendaFuncionarios = pontodevendaFuncionarios;
       this.pontodevendas = pontodevendas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nome", nullable=false, length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="endereco", nullable=false, length=45)
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    
    @Column(name="telefone", nullable=false, length=45)
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    
    @Column(name="cargo", nullable=false)
    public int getCargo() {
        return this.cargo;
    }
    
    public void setCargo(int cargo) {
        this.cargo = cargo;
    }

    
    @Column(name="password", nullable=false)
    public byte[] getPassword() {
        return this.password;
    }
    
    public void setPassword(byte[] password) {
        this.password = password;
    }

    
    @Column(name="userName", unique=true, nullable=false, length=45)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="cpf", unique=true, nullable=false)
    public int getCpf() {
        return this.cpf;
    }
    
    public void setCpf(int cpf) {
        this.cpf = cpf;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="funcionario")
    public Set<Reserva> getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set<Reserva> reservas) {
        this.reservas = reservas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="funcionario")
    public Set<PontodevendaFuncionario> getPontodevendaFuncionarios() {
        return this.pontodevendaFuncionarios;
    }
    
    public void setPontodevendaFuncionarios(Set<PontodevendaFuncionario> pontodevendaFuncionarios) {
        this.pontodevendaFuncionarios = pontodevendaFuncionarios;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="funcionario_has_pontodevenda", catalog="vvv", joinColumns = { 
        @JoinColumn(name="Funcionario_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="PontoDeVenda_id", nullable=false, updatable=false) })
    public Set<Pontodevenda> getPontodevendas() {
        return this.pontodevendas;
    }
    
    public void setPontodevendas(Set<Pontodevenda> pontodevendas) {
        this.pontodevendas = pontodevendas;
    }




}


