package model;
// Generated Mar 2, 2016 5:55:12 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Funcionario generated by hbm2java
 */
public class Funcionario  implements java.io.Serializable {


     private Integer idFuncionario;
     private String nome;
     private String endereco;
     private String telefone;
     private String cargo;
     private String password;
     private String userName;
     private Integer cpf;
     private Set trabalhaPontoDeVendas = new HashSet(0);
     private Set reservas = new HashSet(0);

    public Funcionario() {
    }

    public Funcionario(String nome, String endereco, String telefone, String cargo, String password, String userName, Integer cpf, Set trabalhaPontoDeVendas, Set reservas) {
       this.nome = nome;
       this.endereco = endereco;
       this.telefone = telefone;
       this.cargo = cargo;
       this.password = password;
       this.userName = userName;
       this.cpf = cpf;
       this.trabalhaPontoDeVendas = trabalhaPontoDeVendas;
       this.reservas = reservas;
    }
   
    public Integer getIdFuncionario() {
        return this.idFuncionario;
    }
    
    public void setIdFuncionario(Integer idFuncionario) {
        this.idFuncionario = idFuncionario;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public Integer getCpf() {
        return this.cpf;
    }
    
    public void setCpf(Integer cpf) {
        this.cpf = cpf;
    }
    public Set getTrabalhaPontoDeVendas() {
        return this.trabalhaPontoDeVendas;
    }
    
    public void setTrabalhaPontoDeVendas(Set trabalhaPontoDeVendas) {
        this.trabalhaPontoDeVendas = trabalhaPontoDeVendas;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }




}


