package model;
// Generated Mar 2, 2016 5:55:12 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PontoDeVenda generated by hbm2java
 */
public class PontoDeVenda  implements java.io.Serializable {


     private Integer idPontoDeVenda;
     private String endereco;
     private String nome;
     private String cnpj;
     private String telefone;
     private Set trabalhaPontoDeVendas = new HashSet(0);

    public PontoDeVenda() {
    }

    public PontoDeVenda(String endereco, String nome, String cnpj, String telefone, Set trabalhaPontoDeVendas) {
       this.endereco = endereco;
       this.nome = nome;
       this.cnpj = cnpj;
       this.telefone = telefone;
       this.trabalhaPontoDeVendas = trabalhaPontoDeVendas;
    }
   
    public Integer getIdPontoDeVenda() {
        return this.idPontoDeVenda;
    }
    
    public void setIdPontoDeVenda(Integer idPontoDeVenda) {
        this.idPontoDeVenda = idPontoDeVenda;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public Set getTrabalhaPontoDeVendas() {
        return this.trabalhaPontoDeVendas;
    }
    
    public void setTrabalhaPontoDeVendas(Set trabalhaPontoDeVendas) {
        this.trabalhaPontoDeVendas = trabalhaPontoDeVendas;
    }




}


