package model;
// Generated 13-Mar-2016 22:50:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Pontodevenda generated by hbm2java
 */
@Entity
@Table(name="pontodevenda"
    ,catalog="vvv"
    , uniqueConstraints = @UniqueConstraint(columnNames="cnpj") 
)
public class Pontodevenda  implements java.io.Serializable {


     private Integer id;
     private String endereco;
     private String nome;
     private String cnpj;
     private String telefone;
     private Set<Funcionario> funcionarios = new HashSet<Funcionario>(0);
     private Set<PontodevendaFuncionario> pontodevendaFuncionarios = new HashSet<PontodevendaFuncionario>(0);

    public Pontodevenda() {
    }

	
    public Pontodevenda(String endereco, String nome, String cnpj, String telefone) {
        this.endereco = endereco;
        this.nome = nome;
        this.cnpj = cnpj;
        this.telefone = telefone;
    }
    public Pontodevenda(String endereco, String nome, String cnpj, String telefone, Set<Funcionario> funcionarios, Set<PontodevendaFuncionario> pontodevendaFuncionarios) {
       this.endereco = endereco;
       this.nome = nome;
       this.cnpj = cnpj;
       this.telefone = telefone;
       this.funcionarios = funcionarios;
       this.pontodevendaFuncionarios = pontodevendaFuncionarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="endereco", nullable=false, length=45)
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    
    @Column(name="nome", nullable=false, length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="cnpj", unique=true, nullable=false, length=45)
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }

    
    @Column(name="telefone", nullable=false, length=45)
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="funcionario_has_pontodevenda", catalog="vvv", joinColumns = { 
        @JoinColumn(name="PontoDeVenda_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="Funcionario_id", nullable=false, updatable=false) })
    public Set<Funcionario> getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set<Funcionario> funcionarios) {
        this.funcionarios = funcionarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pontodevenda")
    public Set<PontodevendaFuncionario> getPontodevendaFuncionarios() {
        return this.pontodevendaFuncionarios;
    }
    
    public void setPontodevendaFuncionarios(Set<PontodevendaFuncionario> pontodevendaFuncionarios) {
        this.pontodevendaFuncionarios = pontodevendaFuncionarios;
    }




}


