package model;
// Generated 13-Mar-2016 17:32:36 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PontodevendaFuncionario generated by hbm2java
 */
@Entity
@Table(name="pontodevenda_funcionario"
    ,catalog="vvv"
)
public class PontodevendaFuncionario  implements java.io.Serializable {


     private PontodevendaFuncionarioId id;
     private Funcionario funcionario;
     private Pontodevenda pontodevenda;
     private byte[] escala;

    public PontodevendaFuncionario() {
    }

    public PontodevendaFuncionario(PontodevendaFuncionarioId id, Funcionario funcionario, Pontodevenda pontodevenda, byte[] escala) {
       this.id = id;
       this.funcionario = funcionario;
       this.pontodevenda = pontodevenda;
       this.escala = escala;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pontoDeVendaId", column=@Column(name="PontoDeVenda_id", nullable=false) ), 
        @AttributeOverride(name="funcionarioId", column=@Column(name="Funcionario_id", nullable=false) ) } )
    public PontodevendaFuncionarioId getId() {
        return this.id;
    }
    
    public void setId(PontodevendaFuncionarioId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Funcionario_id", nullable=false, insertable=false, updatable=false)
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PontoDeVenda_id", nullable=false, insertable=false, updatable=false)
    public Pontodevenda getPontodevenda() {
        return this.pontodevenda;
    }
    
    public void setPontodevenda(Pontodevenda pontodevenda) {
        this.pontodevenda = pontodevenda;
    }

    
    @Column(name="escala", nullable=false)
    public byte[] getEscala() {
        return this.escala;
    }
    
    public void setEscala(byte[] escala) {
        this.escala = escala;
    }




}


