package model;
// Generated 13-Mar-2016 14:26:24 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PontodevendaFuncionarioId generated by hbm2java
 */
@Embeddable
public class PontodevendaFuncionarioId  implements java.io.Serializable {


     private int pontoDeVendaId;
     private int funcionarioId;

    public PontodevendaFuncionarioId() {
    }

    public PontodevendaFuncionarioId(int pontoDeVendaId, int funcionarioId) {
       this.pontoDeVendaId = pontoDeVendaId;
       this.funcionarioId = funcionarioId;
    }
   


    @Column(name="PontoDeVenda_id", nullable=false)
    public int getPontoDeVendaId() {
        return this.pontoDeVendaId;
    }
    
    public void setPontoDeVendaId(int pontoDeVendaId) {
        this.pontoDeVendaId = pontoDeVendaId;
    }


    @Column(name="Funcionario_id", nullable=false)
    public int getFuncionarioId() {
        return this.funcionarioId;
    }
    
    public void setFuncionarioId(int funcionarioId) {
        this.funcionarioId = funcionarioId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PontodevendaFuncionarioId) ) return false;
		 PontodevendaFuncionarioId castOther = ( PontodevendaFuncionarioId ) other; 
         
		 return (this.getPontoDeVendaId()==castOther.getPontoDeVendaId())
 && (this.getFuncionarioId()==castOther.getFuncionarioId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPontoDeVendaId();
         result = 37 * result + this.getFuncionarioId();
         return result;
   }   


}


