package model;
// Generated Mar 2, 2016 5:55:12 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Reserva generated by hbm2java
 */
public class Reserva  implements java.io.Serializable {


     private Integer idReserva;
     private Cliente cliente;
     private Funcionario funcionario;
     private Viagem viagem;
     private Date data;
     private Float valor;
     private String status;

    public Reserva() {
    }

	
    public Reserva(Viagem viagem) {
        this.viagem = viagem;
    }
    public Reserva(Cliente cliente, Funcionario funcionario, Viagem viagem, Date data, Float valor, String status) {
       this.cliente = cliente;
       this.funcionario = funcionario;
       this.viagem = viagem;
       this.data = data;
       this.valor = valor;
       this.status = status;
    }
   
    public Integer getIdReserva() {
        return this.idReserva;
    }
    
    public void setIdReserva(Integer idReserva) {
        this.idReserva = idReserva;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public Viagem getViagem() {
        return this.viagem;
    }
    
    public void setViagem(Viagem viagem) {
        this.viagem = viagem;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public Float getValor() {
        return this.valor;
    }
    
    public void setValor(Float valor) {
        this.valor = valor;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


