package model;
// Generated 13-Mar-2016 17:32:36 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reserva generated by hbm2java
 */
@Entity
@Table(name="reserva"
    ,catalog="vvv"
)
public class Reserva  implements java.io.Serializable {


     private Integer id;
     private Cliente cliente;
     private Funcionario funcionario;
     private Viagem viagem;
     private Date data;
     private float valor;
     private String status;

    public Reserva() {
    }

    public Reserva(Cliente cliente, Funcionario funcionario, Viagem viagem, Date data, float valor, String status) {
       this.cliente = cliente;
       this.funcionario = funcionario;
       this.viagem = viagem;
       this.data = data;
       this.valor = valor;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="client_id", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="funcionario_id", nullable=false)
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="viagem_id", nullable=false)
    public Viagem getViagem() {
        return this.viagem;
    }
    
    public void setViagem(Viagem viagem) {
        this.viagem = viagem;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data", nullable=false, length=10)
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }

    
    @Column(name="valor", nullable=false, precision=12, scale=0)
    public float getValor() {
        return this.valor;
    }
    
    public void setValor(float valor) {
        this.valor = valor;
    }

    
    @Column(name="status", nullable=false, length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


