package model;
// Generated Mar 2, 2016 5:55:12 PM by Hibernate Tools 4.3.1



/**
 * TrabalhaPontoDeVenda generated by hbm2java
 */
public class TrabalhaPontoDeVenda  implements java.io.Serializable {


     private TrabalhaPontoDeVendaId id;
     private Funcionario funcionario;
     private PontoDeVenda pontoDeVenda;
     private String diasTrabalho;

    public TrabalhaPontoDeVenda() {
    }

	
    public TrabalhaPontoDeVenda(TrabalhaPontoDeVendaId id, Funcionario funcionario, PontoDeVenda pontoDeVenda) {
        this.id = id;
        this.funcionario = funcionario;
        this.pontoDeVenda = pontoDeVenda;
    }
    public TrabalhaPontoDeVenda(TrabalhaPontoDeVendaId id, Funcionario funcionario, PontoDeVenda pontoDeVenda, String diasTrabalho) {
       this.id = id;
       this.funcionario = funcionario;
       this.pontoDeVenda = pontoDeVenda;
       this.diasTrabalho = diasTrabalho;
    }
   
    public TrabalhaPontoDeVendaId getId() {
        return this.id;
    }
    
    public void setId(TrabalhaPontoDeVendaId id) {
        this.id = id;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public PontoDeVenda getPontoDeVenda() {
        return this.pontoDeVenda;
    }
    
    public void setPontoDeVenda(PontoDeVenda pontoDeVenda) {
        this.pontoDeVenda = pontoDeVenda;
    }
    public String getDiasTrabalho() {
        return this.diasTrabalho;
    }
    
    public void setDiasTrabalho(String diasTrabalho) {
        this.diasTrabalho = diasTrabalho;
    }




}


