package model;
// Generated Mar 2, 2016 5:55:12 PM by Hibernate Tools 4.3.1



/**
 * TrabalhaPontoDeVendaId generated by hbm2java
 */
public class TrabalhaPontoDeVendaId  implements java.io.Serializable {


     private int idFuncionario;
     private int idPontoDeVenda;

    public TrabalhaPontoDeVendaId() {
    }

    public TrabalhaPontoDeVendaId(int idFuncionario, int idPontoDeVenda) {
       this.idFuncionario = idFuncionario;
       this.idPontoDeVenda = idPontoDeVenda;
    }
   
    public int getIdFuncionario() {
        return this.idFuncionario;
    }
    
    public void setIdFuncionario(int idFuncionario) {
        this.idFuncionario = idFuncionario;
    }
    public int getIdPontoDeVenda() {
        return this.idPontoDeVenda;
    }
    
    public void setIdPontoDeVenda(int idPontoDeVenda) {
        this.idPontoDeVenda = idPontoDeVenda;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TrabalhaPontoDeVendaId) ) return false;
		 TrabalhaPontoDeVendaId castOther = ( TrabalhaPontoDeVendaId ) other; 
         
		 return (this.getIdFuncionario()==castOther.getIdFuncionario())
 && (this.getIdPontoDeVenda()==castOther.getIdPontoDeVenda());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdFuncionario();
         result = 37 * result + this.getIdPontoDeVenda();
         return result;
   }   


}


