package model;
// Generated Mar 2, 2016 5:55:12 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Transportadora generated by hbm2java
 */
public class Transportadora  implements java.io.Serializable {


     private Integer idTransportadora;
     private String nome;
     private Set modals = new HashSet(0);

    public Transportadora() {
    }

    public Transportadora(String nome, Set modals) {
       this.nome = nome;
       this.modals = modals;
    }
   
    public Integer getIdTransportadora() {
        return this.idTransportadora;
    }
    
    public void setIdTransportadora(Integer idTransportadora) {
        this.idTransportadora = idTransportadora;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getModals() {
        return this.modals;
    }
    
    public void setModals(Set modals) {
        this.modals = modals;
    }




}


