package model;
// Generated Mar 2, 2016 5:55:12 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Viagem generated by hbm2java
 */
public class Viagem  implements java.io.Serializable {


     private Integer id;
     private Cidade cidadeByCidadeDestinoId;
     private Cidade cidadeByCidadeOrigemId;
     private Date saida;
     private Date chegada;
     private Float valor;
     private Set reservas = new HashSet(0);
     private Set escalas = new HashSet(0);

    public Viagem() {
    }

	
    public Viagem(Cidade cidadeByCidadeDestinoId, Cidade cidadeByCidadeOrigemId) {
        this.cidadeByCidadeDestinoId = cidadeByCidadeDestinoId;
        this.cidadeByCidadeOrigemId = cidadeByCidadeOrigemId;
    }
    public Viagem(Cidade cidadeByCidadeDestinoId, Cidade cidadeByCidadeOrigemId, Date saida, Date chegada, Float valor, Set reservas, Set escalas) {
       this.cidadeByCidadeDestinoId = cidadeByCidadeDestinoId;
       this.cidadeByCidadeOrigemId = cidadeByCidadeOrigemId;
       this.saida = saida;
       this.chegada = chegada;
       this.valor = valor;
       this.reservas = reservas;
       this.escalas = escalas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cidade getCidadeByCidadeDestinoId() {
        return this.cidadeByCidadeDestinoId;
    }
    
    public void setCidadeByCidadeDestinoId(Cidade cidadeByCidadeDestinoId) {
        this.cidadeByCidadeDestinoId = cidadeByCidadeDestinoId;
    }
    public Cidade getCidadeByCidadeOrigemId() {
        return this.cidadeByCidadeOrigemId;
    }
    
    public void setCidadeByCidadeOrigemId(Cidade cidadeByCidadeOrigemId) {
        this.cidadeByCidadeOrigemId = cidadeByCidadeOrigemId;
    }
    public Date getSaida() {
        return this.saida;
    }
    
    public void setSaida(Date saida) {
        this.saida = saida;
    }
    public Date getChegada() {
        return this.chegada;
    }
    
    public void setChegada(Date chegada) {
        this.chegada = chegada;
    }
    public Float getValor() {
        return this.valor;
    }
    
    public void setValor(Float valor) {
        this.valor = valor;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }
    public Set getEscalas() {
        return this.escalas;
    }
    
    public void setEscalas(Set escalas) {
        this.escalas = escalas;
    }




}


