package model;
// Generated 14-Mar-2016 19:47:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.SortedSet;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.OrderBy;

/**
 * Viagem generated by hbm2java
 */
@Entity
@Table(name="viagem"
    ,catalog="vvv"
)
public class Viagem  implements java.io.Serializable {


     private Integer id;
     private float valor;
     private Set<Reserva> reservas;
     private List<Escala> escalas;

    public Viagem() {
    }

	
    public Viagem(float valor) {
        this.valor = valor;
    }
    public Viagem(float valor, Set<Reserva> reservas, List<Escala> escalas) {
       this.valor = valor;
       this.reservas = reservas;
       this.escalas = escalas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="valor", nullable=false, precision=12, scale=0)
    public float getValor() {
        return this.valor;
    }
    
    public void setValor(float valor) {
        this.valor = valor;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="viagem")
    public Set<Reserva> getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set<Reserva> reservas) {
        this.reservas = reservas;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="viagem")
    @OrderBy(clause = "saida ASC")
    public List<Escala> getEscalas() {
        return this.escalas;
    }
    
    public void setEscalas(List<Escala> escalas) {
        this.escalas = escalas;
    }




}


