package model;
// Generated 13-Mar-2016 22:50:52 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Viagem generated by hbm2java
 */
@Entity
@Table(name="viagem"
    ,catalog="vvv"
)
public class Viagem  implements java.io.Serializable {


     private Integer id;
     private Cidade cidadeByCidadeDestinoId;
     private Cidade cidadeByCidadeOrigemId;
     private Date saida;
     private Date chegada;
     private float valor;
     private Set<Reserva> reservas = new HashSet<Reserva>(0);
     private Set<Escala> escalas = new HashSet<Escala>(0);

    public Viagem() {
    }

	
    public Viagem(Cidade cidadeByCidadeDestinoId, Cidade cidadeByCidadeOrigemId, Date saida, Date chegada, float valor) {
        this.cidadeByCidadeDestinoId = cidadeByCidadeDestinoId;
        this.cidadeByCidadeOrigemId = cidadeByCidadeOrigemId;
        this.saida = saida;
        this.chegada = chegada;
        this.valor = valor;
    }
    public Viagem(Cidade cidadeByCidadeDestinoId, Cidade cidadeByCidadeOrigemId, Date saida, Date chegada, float valor, Set<Reserva> reservas, Set<Escala> escalas) {
       this.cidadeByCidadeDestinoId = cidadeByCidadeDestinoId;
       this.cidadeByCidadeOrigemId = cidadeByCidadeOrigemId;
       this.saida = saida;
       this.chegada = chegada;
       this.valor = valor;
       this.reservas = reservas;
       this.escalas = escalas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cidade_destino_id", nullable=false)
    public Cidade getCidadeByCidadeDestinoId() {
        return this.cidadeByCidadeDestinoId;
    }
    
    public void setCidadeByCidadeDestinoId(Cidade cidadeByCidadeDestinoId) {
        this.cidadeByCidadeDestinoId = cidadeByCidadeDestinoId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cidade_origem_id", nullable=false)
    public Cidade getCidadeByCidadeOrigemId() {
        return this.cidadeByCidadeOrigemId;
    }
    
    public void setCidadeByCidadeOrigemId(Cidade cidadeByCidadeOrigemId) {
        this.cidadeByCidadeOrigemId = cidadeByCidadeOrigemId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="saida", nullable=false, length=19)
    public Date getSaida() {
        return this.saida;
    }
    
    public void setSaida(Date saida) {
        this.saida = saida;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="chegada", nullable=false, length=19)
    public Date getChegada() {
        return this.chegada;
    }
    
    public void setChegada(Date chegada) {
        this.chegada = chegada;
    }

    
    @Column(name="valor", nullable=false, precision=12, scale=0)
    public float getValor() {
        return this.valor;
    }
    
    public void setValor(float valor) {
        this.valor = valor;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="viagem")
    public Set<Reserva> getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set<Reserva> reservas) {
        this.reservas = reservas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="viagem")
    public Set<Escala> getEscalas() {
        return this.escalas;
    }
    
    public void setEscalas(Set<Escala> escalas) {
        this.escalas = escalas;
    }




}


