/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import model.Funcionario;

/**
 *
 * @author mateus
 */
public class TelaGerente extends javax.swing.JFrame {
    public Funcionario gerente;
    public TelaPrincipal telaPrincipal;
    public TelaCadastroFuncionario telaCadastroFuncionario = new TelaCadastroFuncionario();
    public TelaCadastroCliente telaCadastroCliente;
    /**
     * Creates new form TelaGerente
     */
    public TelaGerente(Funcionario gerente, TelaPrincipal telaPrincipal) {        
        initComponents();
        this.gerente = gerente;
        this.telaPrincipal = telaPrincipal;
        textoLogado.setText(this.gerente.getNome() + " logado");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastrarFuncionarioButton = new javax.swing.JButton();
        cadastrarClienteButton = new javax.swing.JButton();
        irViagensButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        textoLogado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cadastrarFuncionarioButton.setText("Cadastrar Funcionário");
        cadastrarFuncionarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarFuncionarioButtonActionPerformed(evt);
            }
        });

        cadastrarClienteButton.setText("Cadastrar Cliente");
        cadastrarClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarClienteButtonActionPerformed(evt);
            }
        });

        irViagensButton.setText("Ir para viagens");
        irViagensButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irViagensButtonActionPerformed(evt);
            }
        });

        logoutButton.setText("Logout");

        textoLogado.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(irViagensButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cadastrarFuncionarioButton, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(cadastrarClienteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoLogado, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(textoLogado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cadastrarFuncionarioButton)
                .addGap(18, 18, 18)
                .addComponent(cadastrarClienteButton)
                .addGap(18, 18, 18)
                .addComponent(irViagensButton)
                .addGap(23, 23, 23)
                .addComponent(logoutButton)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarFuncionarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarFuncionarioButtonActionPerformed
        this.setVisible(false);
        telaCadastroFuncionario.telaGerente = this;
        telaCadastroFuncionario.setVisible(true);
    }//GEN-LAST:event_cadastrarFuncionarioButtonActionPerformed

    private void cadastrarClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarClienteButtonActionPerformed
        telaCadastroCliente = new TelaCadastroCliente(null, this);
        this.setVisible(false);
        telaCadastroCliente.setVisible(true);
    }//GEN-LAST:event_cadastrarClienteButtonActionPerformed

    private void irViagensButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irViagensButtonActionPerformed
        
    }//GEN-LAST:event_irViagensButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarClienteButton;
    private javax.swing.JButton cadastrarFuncionarioButton;
    private javax.swing.JButton irViagensButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JTextField textoLogado;
    // End of variables declaration//GEN-END:variables
}
